name: "Test `fpc` inside Nix"
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        lang: [C, FPC]
        suffix: [""]
        include:
          - lang: FPC
            suffix: "-verbose"
      fail-fast: false
    name: Build ${{ matrix.lang }}${{ matrix.suffix }} program
    runs-on: macos-13
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz"
    - name: Build
      run: nix-build "$(tr A-Z a-z <<< ${{ matrix.lang }})-test${{ matrix.suffix }}.nix"
    - name: Upload `.drv`s and logs
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.lang }}-build-log
        path: |
          /nix/store/*aaa-*-test*.drv
          /nix/var/log/nix/drvs/*/*aaa-*-test*
        if-no-files-found: ignore
